import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ContainerWrapper from "@/app/components/container-wrapper";
import AuthProvider from "@/app/providers/auth";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Credenly",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <ContainerWrapper>{children}</ContainerWrapper>
        </AuthProvider>
      </body>
    </html>
  );
}
